name: wallet_apps
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  line_icons: ^2.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
